version: "3.9" 
services:
  botnya:
    build: .
    ports:
      - "8080"
    volumes:
      - .:/app
      - meky:/var/log
    links:
      - redis
  redisnya:
    image: redis
volumes:
  meky: {}